### ISSUE TITLE
Hide status bar in viewController

### ISSUE THREAD

**Issue by otymartin** [dk53/AutomaticStatusBarColor#3]
@dk53 
Since i set `viewcontrollerbased status bar` property in plist to `NO`, How do I hide the status bar in some of my VC's like `cameraview`

**Comment by otymartin** [comment]
@dk53 
**Update**
I set this in viewDidLOad, it crashes sometimes,.
I set in viewWillAppear, nothing happens.
disableAutomaticStatusBarColor()

**Comment by dk53** [comment]
Hello @otymartin ! 
AutomaticStatusBar color is not supposed to hide the status bar. For that you need to override the getter prefersStatusBarHidden and return true.

ASB is just about the status bar color, hitting disableAutomaticStatusBarColor will just disable the framework for the ViewController !
